name: mera_ashiana
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  connectivity_plus: ^7.0.0
  image_picker: ^1.1.2
  google_sign_in: ^7.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Launcher icons should be a dev_dependency
  flutter_launcher_icons: ^0.14.4

# Correct configuration for the icon generator
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/ic_launcher.png"
  # This makes the icon look better on modern Android devices
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/lottie/
    - assets/images/